# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

# Variables used in this pipeline are defined in `shared-pipeline-vars`, which is `source`'d before calling `buidkite-agent pipeline upload`

agents:
  queue: android

steps:
  - label: ✅ Gradle Wrapper Validation
    command: validate_gradle_wrapper
    agents:
      queue: linter
    notify:
      - github_commit_status:
          context: Gradle Wrapper Validation

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  - label: ":danger: Danger - PR Check"
    command: danger
    key: danger
    if: build.pull_request.id != null
    retry:
      manual:
        permit_on_passed: true
    agents:
      queue: linter
    notify:
      - github_commit_status:
          context: Danger - PR Check

  - label: ⚒️ Build
    command: ./gradlew assembleDebug
    notify:
      - github_commit_status:
          context: Build

  - label: 🧪 Unit tests
    command: ./gradlew testDebug
    artifact_paths:
      - "**/build/test-results/*/*.xml"
    notify:
      - github_commit_status:
          context: Unit tests

  - label: 🕵️‍♂️ Lint
    command: |
      ./gradlew :app:lintDebug
      
      upload_sarif_to_github 'app/build/reports/lint-results-debug.sarif'
    plugins: [$CI_TOOLKIT]
    artifact_paths:
      - "**/build/reports/lint-results*.*"
    notify:
      - github_commit_status:
          context: Lint

  - label: 🕵️ Detekt
    command: |
      ./gradlew detekt
      
      upload_sarif_to_github 'app/build/reports/detekt/detekt.sarif'
    plugins: [$CI_TOOLKIT]
    artifact_paths:
      - "**/build/reports/detekt/*.*"
    notify:
      - github_commit_status:
          context: Detekt

  - label: 🧪📸 Screenshot tests
    command: |
      echo "--- 🧪📸 Screenshot Testing"
      ./gradlew verifyRoborazziDebug -Pscreenshot
    artifact_paths:
      - "**/build/test-results/*/*.xml"
    notify:
      - github_commit_status:
          context: Screenshot tests


  ################################
  # Run Prototype Build on demand
  ################################

  - block: On Demand Prototype Build
    if: build.pull_request.id != null
    key: run-on-demand-prototype-build
    prompt: Build Pull Request Prototype?
    blocked_state: passed

  - label: 🏗️ Prototype Build
    if: build.pull_request.id != null
    depends_on:
      - run-on-demand-prototype-build
    command: .buildkite/commands/prototype-build.sh
    plugins: [$CI_TOOLKIT]
    artifact_paths:
      - "**/build/outputs/apk/**/*"
