# frozen_string_literal: true

default_platform(:android)

UI.user_error!('Please run fastlane via `bundle exec`') unless FastlaneCore::Helper.bundler?

########################################################################
# Constants
########################################################################

PROTOTYPE_BUILD_DOMAIN = 'https://cdn.a8c-ci.services'
PROTOTYPE_BUILD_TYPE = 'release'

platform :android do
  # Builds the Gravatar Demo app prototype APK, uploads it to S3, and posts a download link as a comment on the associated pull request.
  #
  # Intended for use in CI to provide reviewers with an installable build for testing.
  # @env [String] BUILDKITE_ARTIFACTS_S3_BUCKET The S3 bucket to upload artifacts to. Must be set.
  # @env [String] BUILDKITE_PULL_REQUEST The pull request number.
  #
  lane :build_and_upload_prototype_build do
    UI.user_error!("'BUILDKITE_ARTIFACTS_S3_BUCKET' must be defined as an environment variable.") unless ENV['BUILDKITE_ARTIFACTS_S3_BUCKET']

    comment_params = {
      project: 'Automattic/Gravatar-Android',
      pr_number: Integer(ENV.fetch('BUILDKITE_PULL_REQUEST', nil)),
      reuse_identifier: 'app-prototype-build-link'
    }

    comment_on_pr(
      **comment_params,
      body: '🚧 Prototype build will be available soon'
    )

    gradle(
      task: 'assemble',
      build_type: PROTOTYPE_BUILD_TYPE
    )

    upload_path = upload_to_s3(
      bucket: 'a8c-apps-public-artifacts',
      key: "gravatar-app-prototype-build-#{generate_prototype_build_number}.apk",
      file: lane_context[SharedValues::GRADLE_ALL_APK_OUTPUT_PATHS].first,
      if_exists: :skip
    )

    install_url = "#{PROTOTYPE_BUILD_DOMAIN}/#{upload_path}"

    comment_body = prototype_build_details_comment(
      app_display_name: 'Gravatar Android',
      download_url: install_url,
      metadata: {
        'Build Type': PROTOTYPE_BUILD_TYPE
      },
      fold: true
    )

    comment_on_pr(
      **comment_params,
      body: comment_body
    )
  end

  def generate_prototype_build_number
    if ENV['BUILDKITE']
      commit = ENV.fetch('BUILDKITE_COMMIT', nil)[0, 7]
      branch = ENV['BUILDKITE_BRANCH'].parameterize
      pr_num = ENV.fetch('BUILDKITE_PULL_REQUEST', nil)

      pr_num == 'false' ? "#{branch}-#{commit}" : "pr#{pr_num}-#{commit}"
    else
      repo = Git.open(PROJECT_ROOT_FOLDER)
      commit = repo.current_branch.parameterize
      branch = repo.revparse('HEAD')[0, 7]

      "#{branch}-#{commit}"
    end
  end
end
