# frozen_string_literal: true

default_platform(:android)

UI.user_error!('Please run fastlane via `bundle exec`') unless FastlaneCore::Helper.bundler?

########################################################################
# Constants
########################################################################
DEFAULT_BRANCH = 'trunk'

BUILDKITE_ORG_NAME = 'automattic'
BUILDKITE_PIPELINE = 'gravatar-android'

PROJECT_ROOT_FOLDER = File.dirname(File.expand_path(__dir__))

VERSION_PROPERTIES_PATH = File.join(PROJECT_ROOT_FOLDER, 'version.properties')
VERSION_FILE = Fastlane::Wpmreleasetoolkit::Versioning::AndroidVersionFile.new(version_properties_path: VERSION_PROPERTIES_PATH)

VERSION_CALCULATOR = Fastlane::Wpmreleasetoolkit::Versioning::SemanticVersionCalculator.new
VERSION_FORMATTER = Fastlane::Wpmreleasetoolkit::Versioning::RCNotationVersionFormatter.new
BUILD_CODE_CALCULATOR = Fastlane::Wpmreleasetoolkit::Versioning::SimpleBuildCodeCalculator.new
BUILD_CODE_FORMATTER = Fastlane::Wpmreleasetoolkit::Versioning::SimpleBuildCodeFormatter.new

PROTOTYPE_BUILD_DOMAIN = 'https://cdn.a8c-ci.services'
RELEASE_BUILD_TYPE = 'Release'

platform :android do
  # Builds a release app bundle .aab
  #
  lane :build_bundle do
    gradle(task: 'clean')

    gradle(
      task: 'bundle',
      build_type: RELEASE_BUILD_TYPE
    )
  end

  # Uploads the app bundle to the Google Play Store
  #
  # @param track [String] The track to upload to. One of: 'internal', 'alpha', 'beta', 'production'.
  # @param release_status [String] The release status. One of: 'completed', 'draft', 'halted', 'inProgress'.
  # @param rollout [String] The percentage of users who should get the update, as a string between '0' and '1'.
  # @env [String] PLAY_STORE_RAW_JSON_KEY The Google Play Store service account JSON key data
  #
  lane :upload_to_store do |track:, release_status:, rollout:|
    require_env_vars!('PLAY_STORE_RAW_JSON_KEY')

    upload_to_play_store(
      package_name: 'com.gravatar.app',
      aab: File.join(PROJECT_ROOT_FOLDER, 'app', 'build', 'outputs', 'bundle', 'release', 'app-release.aab'),
      track: track,
      release_status: release_status,
      rollout: rollout,
      skip_upload_metadata: (track != 'production'),
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      json_key_data: ENV.fetch('PLAY_STORE_RAW_JSON_KEY', nil)
    )
  end

  # Builds the Gravatar Demo app prototype APK, uploads it to S3, and posts a download link as a comment on the associated pull request.
  #
  # Intended for use in CI to provide reviewers with an installable build for testing.
  # @env [String] BUILDKITE_ARTIFACTS_S3_BUCKET The S3 bucket to upload artifacts to. Must be set.
  # @env [String] BUILDKITE_PULL_REQUEST The pull request number.
  #
  lane :build_and_upload_prototype_build do
    require_env_vars!('BUILDKITE_ARTIFACTS_S3_BUCKET')

    comment_params = {
      project: 'Automattic/Gravatar-Android',
      pr_number: Integer(ENV.fetch('BUILDKITE_PULL_REQUEST', nil)),
      reuse_identifier: 'app-prototype-build-link'
    }

    comment_on_pr(
      **comment_params,
      body: '🚧 Prototype build will be available soon'
    )

    gradle(
      task: 'assemble',
      build_type: RELEASE_BUILD_TYPE
    )

    upload_path = upload_to_s3(
      bucket: 'a8c-apps-public-artifacts',
      key: "gravatar-app-prototype-build-#{generate_prototype_build_number}.apk",
      file: lane_context[SharedValues::GRADLE_ALL_APK_OUTPUT_PATHS].first,
      if_exists: :skip
    )

    install_url = "#{PROTOTYPE_BUILD_DOMAIN}/#{upload_path}"

    comment_body = prototype_build_details_comment(
      app_display_name: 'Gravatar Android',
      download_url: install_url,
      metadata: {
        'Build Type': RELEASE_BUILD_TYPE
      },
      fold: true
    )

    comment_on_pr(
      **comment_params,
      body: comment_body
    )
  end

  lane :build_and_upload_to_play_store do |track: 'internal', release_status: 'draft'|
    # TODO: using `internal`` track with `draft` releases by default while the release itself is in draft mode
    build_bundle
    upload_to_store(track: track, release_status: release_status, rollout: '1')
  end

  #####################################################################################
  # Release lanes & utils
  #####################################################################################
  lane :new_alpha_release do |skip_confirm: false|
    require_env_vars!('BUILDKITE_TOKEN')
    ensure_git_status_clean

    UI.important <<~PROMPT
      Initiating a new alpha release.
      This will:
      - Checkout and pull the #{DEFAULT_BRANCH} branch (if running on CI)
      - Bump the build code from #{build_code_current} to #{build_code_next}
      - Trigger a new alpha build in Buildkite
    PROMPT
    next unless skip_confirm || UI.confirm('Continue?')

    Fastlane::Helper::GitHelper.checkout_and_pull(DEFAULT_BRANCH) if is_ci?

    bump_build_code

    push_to_git_remote

    trigger_release_build
  end

  # Trigger a new alpha build on CI
  #
  lane :trigger_release_build do
    require_env_vars!('BUILDKITE_TOKEN')

    trigger_buildkite_build(
      branch: git_branch,
      pipeline: 'release-builds.yml',
      message: "Release Build (#{build_code_current})"
    )
  end

  def trigger_buildkite_build(branch:, pipeline:, message: nil)
    environment = {
      'RELEASE_VERSION' => release_version_current
    }

    common_args = {
      pipeline_file: pipeline,
      branch: branch,
      message: message || "Build #{pipeline.sub('.yml', '')}",
      environment: environment
    }

    if is_ci?
      buildkite_add_trigger_step(**common_args)
    else
      # For local development, call Buildkite API to start a new build
      buildkite_trigger_build(
        buildkite_organization: BUILDKITE_ORG_NAME,
        buildkite_pipeline: BUILDKITE_PIPELINE,
        **common_args
      )
    end
  end
end

#####################################################################################
# Versioning utils
#####################################################################################

# Updates the build code in version.properties to the next build code and commits the change
#
def bump_build_code
  VERSION_FILE.write_version(
    version_name: release_version_current,
    version_code: build_code_next
  )
  commit_version_update(message: '[skip ci] Bump build code')
end

# Updates the version name in version.properties to the next release version and commits the change
#
def bump_version
  VERSION_FILE.write_version(
    version_name: release_version_next
  )
  commit_version_update(message: '[skip ci] Bump app version')
end

# Commits the version update to the version.properties file
#
def commit_version_update(message:)
  Fastlane::Helper::GitHelper.commit(
    message: message,
    files: VERSION_PROPERTIES_PATH
  )
end

# Returns the current version name from `version.properties` without needing formatting or calculations
#
def version_name_current
  VERSION_FILE.read_version_name
end

# Returns the release version of the app in the format `1.2` or `1.2.3` if it is a hotfix
#
def release_version_current
  current_version = VERSION_FORMATTER.parse(version_name_current)
  VERSION_FORMATTER.release_version(current_version)
end

#  Returns the next release version of the app in the format `1.2` or `1.2.3` if it is a hotfix
#
def release_version_next
  current_version = VERSION_FORMATTER.parse(version_name_current)
  release_version_next = VERSION_CALCULATOR.next_release_version(version: current_version)
  VERSION_FORMATTER.release_version(release_version_next)
end

# Returns the current build code of the app
#
def build_code_current
  build_code_current = VERSION_FILE.read_version_code
  BUILD_CODE_FORMATTER.build_code(build_code: build_code_current)
end

# Returns the next build code of the app
#
def build_code_next
  build_code_current = VERSION_FILE.read_version_code
  build_code_next = BUILD_CODE_CALCULATOR.next_build_code(build_code: build_code_current)
  BUILD_CODE_FORMATTER.build_code(build_code: build_code_next)
end

# Generates a build number for the prototype build
#
def generate_prototype_build_number
  if ENV['BUILDKITE']
    commit = ENV.fetch('BUILDKITE_COMMIT', nil)[0, 7]
    branch = ENV['BUILDKITE_BRANCH'].parameterize
    pr_num = ENV.fetch('BUILDKITE_PULL_REQUEST', nil)

    pr_num == 'false' ? "#{branch}-#{commit}" : "pr#{pr_num}-#{commit}"
  else
    repo = Git.open(PROJECT_ROOT_FOLDER)
    commit = repo.current_branch.parameterize
    branch = repo.revparse('HEAD')[0, 7]

    "#{branch}-#{commit}"
  end
end

#####################################################################################
# Other utils
#####################################################################################

def require_env_vars!(*keys)
  keys.each do |key|
    UI.user_error!("Environment variable '#{key}' is not set.") unless ENV.key?(key)
  end
end
